#!/bin/sh
PIDFILE=/local/triggr-server/triggr.pid

PID=$(cat ${PIDFILE})

kill -INT ${PID}

while [ -x /proc/${PID} ]                    
do                                           
    echo "Waiting for Triggr to shutdown ..."
    sleep 1                                  
done                                         
echo "Triggr stopped"                        

case "$1" in
    --remove-logs)
	echo "Removing log files"
	rm -f *.log*
	exit 0
	;;
    *)
	break
	;;
esac